name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
       os: [ubuntu-latest , windows-latest , macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .  --tag fatibi/work_simple:$(date +%s)
      
    - name: secret key
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
