name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
  

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      

     

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          image: fatibi/work_simple
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      

      
