name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: postgres

    steps:
    - uses: fatibi/work_simple
    - name: Build the Docker image
      run: docker build . 
